export const CANCEL_ACCEPTED_CLAIM_MODAL = 'CANCEL_ACCEPTED_CLAIM_MODAL';
export const ACCEPT_CANCEL_CLAIM_MODAL = 'ACCEPT_CANCEL_CLAIM_MODAL';
export const CANCEL_SHIFT_MODAL = 'CANCEL_SHIFT_MODAL';
export const NETWORK_ERROR_MODAL = 'NETWORK_ERROR_MODAL';
export const SERVER_ERROR_MODAL = 'SERVER_ERROR_MODAL';
export const SERVER_TIMEOUT_MODAL = 'SERVER_TIMEOUT_MODAL';
