export enum StorageKeys {
    USER_TOKEN_KEY = 'USER_TOKEN',
    USER_TOKEN_DEPRECATED_KEY = 'USER_TOKEN_DEPRECATED',
    HAS_MIGRATED_TOKENS_SECURITY = 'HAS_MIGRATED_TOKENS_SECURITY',
    LAST_PROFILE_LOCALE = 'LAST_PROFILE_LOCALE',
    EMAIL_KEY = 'EMAIL_KEY'
}
